using System.Collections.ObjectModel;
using System.Windows;
using System.Windows.Controls;
using Microsoft.Win32;
using V2RaySybau.Core;
using V2RaySybau.Infrastructure;
using V2RaySybau.Models;
using V2RaySybau.Profiles;
using V2RaySybau.Settings;
using V2RaySybau.Storage;
namespace V2RaySybau.UI;
public partial class MainWindow : Window
{
    private readonly ProfileStore _store = new(); private readonly ProfileImportService _importer = new(); private readonly SettingsService _settingsStore = new(); private readonly WindowsIntegrationService _windows = new(); private readonly CoreProcessService _core = new();
    private readonly ObservableCollection<ConnectionProfile> _profiles = []; private AppSettings _settings = new(); private bool _isLoading;
    public MainWindow() { InitializeComponent(); Loaded += OnLoaded; Closing += async (_, _) => { _settings.AutoConnect = AutoConnect.IsChecked == true; await _settingsStore.SaveAsync(_settings); await _store.SaveAsync(_profiles); await _core.DisposeAsync(); }; _core.EventReceived += (_, e) => Log.Items.Insert(0, $"{e.At:HH:mm:ss} [{e.Level}] {e.Message}"); }
    private async void OnLoaded(object sender, RoutedEventArgs e) { _isLoading = true; _settings = await _settingsStore.LoadAsync(); foreach (var item in await _store.LoadAsync()) _profiles.Add(item); Profiles.ItemsSource = _profiles; SystemProxy.IsChecked = _settings.SystemProxy; Autostart.IsChecked = _settings.StartWithWindows; AutoConnect.IsChecked = _settings.AutoConnect; Theme.SelectedIndex = (int)_settings.Theme; Language.SelectedIndex = _settings.Language == "ru" ? 1 : _settings.Language == "en" ? 2 : 0; Language.SelectionChanged += (_, _) => _settings.Language = Language.SelectedIndex == 1 ? "ru" : Language.SelectedIndex == 2 ? "en" : "auto"; RefreshGroups(); if (_settings.AutoConnect && _settings.LastProfileId is { } id) { Profiles.SelectedItem = _profiles.FirstOrDefault(x => x.Id == id); await ConnectSelectedAsync(); } _isLoading = false; }
    private async void Import_Click(object sender, RoutedEventArgs e) { var text = Clipboard.ContainsText() ? Clipboard.GetText() : ""; if (string.IsNullOrWhiteSpace(text)) { MessageBox.Show("Скопируйте VLESS/VMess URI или URL подписки в буфер обмена."); return; } try { var imported = Uri.TryCreate(text.Trim(), UriKind.Absolute, out var url) && (url.Scheme is "http" or "https") ? await _importer.ImportSubscriptionAsync(url.ToString(), new HttpClient()) : _importer.Import(text); foreach (var profile in imported) _profiles.Add(profile); RefreshGroups(); Log.Items.Insert(0, $"Импортировано профилей: {imported.Count}"); } catch (Exception ex) { MessageBox.Show(ex.Message, "Ошибка импорта"); } }
    private void Export_Click(object sender, RoutedEventArgs e) { var selected = Profiles.SelectedItems.Cast<ConnectionProfile>().ToList(); if (selected.Count == 0 && Profiles.SelectedItem is ConnectionProfile one) selected.Add(one); if (selected.Count == 0) return; var dialog = new SaveFileDialog { Filter = "JSON files|*.json", FileName = "v2raysybau-profiles.json" }; if (dialog.ShowDialog() == true) File.WriteAllText(dialog.FileName, _store.Export(selected)); }
    private void Delete_Click(object sender, RoutedEventArgs e) { if (Profiles.SelectedItem is not ConnectionProfile profile) return; if (MessageBox.Show($"Удалить профиль «{profile.Name}»?", "Подтвердите удаление", MessageBoxButton.YesNo, MessageBoxImage.Warning) == MessageBoxResult.Yes) { _profiles.Remove(profile); ClearEditor(); RefreshGroups(); } }
    private async void Connect_Click(object sender, RoutedEventArgs e) => await ConnectSelectedAsync();
    private async Task ConnectSelectedAsync() { if (Profiles.SelectedItem is not ConnectionProfile profile) { MessageBox.Show("Выберите профиль."); return; } if (_core.IsRunning) { await _core.StopAsync(); ConnectButton.Content = "Подключить"; return; } var exe = Path.Combine(AppContext.BaseDirectory, "core", "xray.exe"); if (!File.Exists(exe)) { MessageBox.Show("Поместите совместимое xray.exe или v2ray.exe в папку core приложения."); return; } await _core.StartAsync(exe, new XrayConfigAdapter().Build(profile)); _settings.LastProfileId = profile.Id; ConnectButton.Content = "Отключить"; }
    private void Profiles_SelectionChanged(object sender, SelectionChangedEventArgs e) { if (Profiles.SelectedItem is ConnectionProfile p) { NameBox.Text = p.Name; HostBox.Text = p.Host; PortBox.Text = p.Port.ToString(); UserIdBox.Text = p.UserId; GroupBox.Text = p.Group; } }
    private void SaveEditor(object sender, RoutedEventArgs e) { if (Profiles.SelectedItem is not ConnectionProfile p) return; p.Name = NameBox.Text; p.Host = HostBox.Text; p.UserId = UserIdBox.Text; p.Group = string.IsNullOrWhiteSpace(GroupBox.Text) ? "Default" : GroupBox.Text; if (int.TryParse(PortBox.Text, out var port)) p.Port = port; RefreshGroups(); }
    private void SystemProxy_Changed(object sender, RoutedEventArgs e) { if (_isLoading) return; _settings.SystemProxy = SystemProxy.IsChecked == true; _windows.SetSystemProxy(_settings.SystemProxy); }
    private void Autostart_Changed(object sender, RoutedEventArgs e) { if (_isLoading) return; _settings.StartWithWindows = Autostart.IsChecked == true; _windows.SetAutostart(_settings.StartWithWindows); }
    private void Theme_SelectionChanged(object sender, SelectionChangedEventArgs e) { if (_isLoading) return; _settings.Theme = (ThemeMode)Math.Max(0, Theme.SelectedIndex); var dark = _settings.Theme == ThemeMode.Dark; Background = dark ? new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(30, 30, 30)) : System.Windows.Media.Brushes.White; }
    private void GroupFilter_SelectionChanged(object sender, SelectionChangedEventArgs e) { if (GroupFilter.SelectedItem is string group && group != "Все") Profiles.ItemsSource = new ObservableCollection<ConnectionProfile>(_profiles.Where(x => x.Group == group)); else Profiles.ItemsSource = _profiles; }
    private void RefreshGroups() { var chosen = GroupFilter.SelectedItem as string; GroupFilter.ItemsSource = new[] { "Все" }.Concat(_profiles.Select(x => x.Group).Distinct()).ToList(); GroupFilter.SelectedItem = chosen ?? "Все"; }
    private void ClearEditor() { NameBox.Clear(); HostBox.Clear(); PortBox.Clear(); UserIdBox.Clear(); GroupBox.Clear(); }
}
